apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: i220878/cartservice:9aae076
          ports:
            - containerPort: 7070
          env:
            # Tell the cart service to use in-memory storage (no Redis needed)
            - name: REDIS_ADDR
              value: ""
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

